# Welcome to Jekyll!
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

name: Fabian SCheuermann
title: Fabian Scheuermann 
email: f.scheuermann@uni-heidelberg.de
description: My first webpage
include: [_pages]
github_username:  fschmnn

# Build settings
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed


# create permalink for posts and pages
#defaults:
#  -
#    scope:
#      type: posts
#      path: _posts
#    values:
#      isPost: true
#      layout: post
#      permalink: /blog/:categories/:title/
#  -
#    scope:
#      type: pages
#      path: _pages
#    values:
#      isPost: false
#      layout: default
