# Welcome to Jekyll!
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

name: Fabian Scheuermann
title: Fabian Scheuermann 
email: f.scheuermann@uni-heidelberg.de

description: This is the personal website of Fabian Scheuermann, PhD student in Astronomy at Heidelberg University
include: [_pages]

# Build settings
theme: minima
markdown: kramdown

# Google Analytics
google_analytics: UA-165271804-1

# create permalink for posts and pages
defaults:
  -
    scope:
      type: posts
      path: _posts
    values:
      isPost: true
      layout: post
      permalink: /blog/:categories/:title/
  -
    scope:
      type: pages
      path: _pages
    values:
      isPost: false
      layout: default

# define the items that appear in the footer
external:              
  - {title: ADS, icon: ads_bw, width:50, url: "https://ui.adsabs.harvard.edu/search/q=orcid%3A0000-0003-2707-4678&sort=date%20desc%2C%20bibcode%20desc&p_=0"}
  - {title: ORCID, icon: orcid_bw, url: "https://orcid.org/0000-0003-2707-4678"}
  - {title: GoogleScholar, icon: google_bw, url: "https://scholar.google.com/citations?user=58UwVOcAAAAJ"}
  - {title: Github, icon: GitHub_bw, url: "https://github.com/fschmnn"}
  - {title: LinkedIn, icon: linkedin_bw, url: "https://de.linkedin.com/in/fschmnn"}
  #- {title: Twitter, icon: twitter_bw, url: "https://twitter.com/fschmnn"}
  - {title: Letterboxd, icon: letterboxd_bw, url: "https://letterboxd.com/jukeboxhero/"}

plugins:
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap